version: '3.8'
services:
  c_orderservice:
    container_name: "order_service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6060:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - ecom_network

  mssql-server:
    container_name: "order_db"
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "123Qwe123."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - ecom_network

networks:
  ecom_network:
    external: true

volumes:
  mssql-data:
    driver: local